### ISSUE TITLE
方便的话，能否告知一下运行这套代码的运行环境呢？

### ISSUE THREAD

**Issue by liofoil** [daiyongya/markbert#2]
如题

**Comment by daiyongya** [comment]
python3.7/3.8, pytorch, transformers包是必须，版本应该是兼容的，其他应该不缺了，你运行的时候万一再缺什么, pip install一下。如果想用其他中文分词器来做分词，再装一下其他分词包

**Comment by liofoil** [comment]
好的，我已经配置成功了，谢谢
